# Generated by Django 6.0 on 2025-12-19 07:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('total_gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_amount_after_gst', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('orderno', models.CharField(blank=True, max_length=50, null=True)),
                ('billno', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('transportmode', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicleno', models.CharField(blank=True, max_length=10, null=True)),
                ('dateofsupply', models.DateField(blank=True, null=True)),
                ('placeofsupply', models.CharField(blank=True, max_length=50, null=True)),
                ('gstrc', models.IntegerField(blank=True, null=True)),
                ('tc', models.CharField(default='All Disputes subject to Hisar Jurisdiction. Goods once sold will not be taken back or exchanged. Interest @24% will be charged if bills not paid at presentation. E.& O.E.', max_length=500)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.client')),
            ],
            options={
                'db_table': 'billdetails',
                'ordering': ('-date', '-billno'),
                'get_latest_by': ['-billno'],
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('hsncode', models.IntegerField(blank=True, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('product_discription', models.TextField(default='')),
                ('product_quantity', models.IntegerField(default=1)),
                ('unit_type', models.CharField(blank=True, choices=[('BAG', 'BAGS'), ('BAL', 'BALE'), ('BDL', 'BUNDLES'), ('BKL', 'BUCKLES'), ('BOU', 'BILLIONS OF UNITS'), ('BOX', 'BOX'), ('BTL', 'BOTTLES'), ('BUN', 'BUNCHES'), ('CAN', 'CANS'), ('CBM', 'CUBIC METER'), ('CCM', 'CUBIC CENTIMETER'), ('CMS', 'CENTIMETER'), ('CTN', 'CARTONS'), ('DOZ', 'DOZEN'), ('DRM', 'DRUM'), ('GGR', 'GREAT GROSS'), ('GMS', 'GRAMS'), ('GRS', 'GROSS'), ('GYD', 'GROSS YARDS'), ('KGS', 'KILOGRAMS'), ('KLR', 'KILOLITRE'), ('KME', 'KILOMETRE'), ('MLT', 'MILLILITRE'), ('MTR', 'METERS'), ('MTS', 'METRIC TON'), ('NOS', 'NUMBERS'), ('PAC', 'PACKS'), ('PCS', 'PIECES'), ('PRS', 'PAIRS'), ('QTL', 'QUINTAL'), ('ROL', 'ROLLS'), ('SET', 'SETS'), ('SQF', 'SQUARE FEET'), ('SQM', 'SQUARE METERS'), ('SQY', 'SQUARE YARDS'), ('TBS', 'TABLETS'), ('TGM', 'TEN GRAMS'), ('THD', 'THOUSANDS'), ('TON', 'TONNES'), ('TUB', 'TUBES'), ('UGS', 'US GALLONS'), ('UNT', 'UNITS'), ('YDS', 'YARDS'), ('OTH', 'OTHERS')], max_length=3, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'productdetails',
            },
        ),
        migrations.CreateModel(
            name='QuotationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('total_gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_amount_after_gst', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('quotationno', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('tc', models.CharField(default='1. 100% ADVANCE 2. Service within 7 days after order confirmation 3. Quoted Rate validity is 30 Days from quotation date', max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'db_table': 'quotaiondetails',
                'ordering': ('-quotationno',),
            },
        ),
    ]
