# Generated by Django 6.0 on 2025-12-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=70, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('salogan', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('pincode', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('statecode', models.CharField(choices=[('1', 'JAMMU AND KASHMIR'), ('2', 'HIMACHAL PRADESH'), ('3', 'PUNJAB'), ('4', 'CHANDIGARH'), ('5', 'UTTARAKHAND'), ('6', 'HARYANA'), ('7', 'DELHI'), ('8', 'RAJASTHAN'), ('9', 'UTTAR PRADESH'), ('10', 'BIHAR'), ('11', 'SIKKIM'), ('12', 'ARUNACHAL PRADESH'), ('13', 'NAGALAND'), ('14', 'MANIPUR'), ('15', 'MIZORAM'), ('16', 'TRIPURA'), ('17', 'MEGHLAYA'), ('18', 'ASSAM'), ('19', 'WEST BENGAL'), ('20', 'JHARKHAND'), ('21', 'ODISHA'), ('22', 'CHATTISGARH'), ('23', 'MADHYA PRADESH'), ('24', 'GUJARAT'), ('25', 'DAMAN AND DIU'), ('26', 'DADRA AND NAGAR HAVELI'), ('27', 'MAHARASHTRA'), ('28', 'ANDHRA PRADESH(BEFORE DIVISION)'), ('29', 'KARNATAKA'), ('30', 'GOA'), ('31', 'LAKSHWADEEP'), ('32', 'KERALA'), ('33', 'TAMIL NADU'), ('34', 'PUDUCHERRY'), ('35', 'ANDAMAN AND NICOBAR ISLANDS'), ('36', 'TELANGANA'), ('37', 'ANDHRA PRADESH (NEW)')], max_length=2)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_account', models.CharField(max_length=20)),
                ('bank_ifsc', models.CharField(max_length=11)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
